"""auto migration

Revision ID: 0920306b87ba
Revises: c7f8bff397a2
Create Date: 2026-03-04 21:44:20.551749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0920306b87ba'
down_revision: Union[str, Sequence[str], None] = 'c7f8bff397a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('task_comments', 'task_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('task_comments', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
