"""update user model for fastapi-users

Revision ID: 50386824ebe9
Revises: 3e4b1c3a266e
Create Date: 2026-01-31 19:44:51.807436

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50386824ebe9'
down_revision: Union[str, Sequence[str], None] = '3e4b1c3a266e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
