"""add nickname to user

Revision ID: c7f8bff397a2
Revises: 2a4a153b31f4
Create Date: 2026-02-16 02:08:43.329489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7f8bff397a2'
down_revision: Union[str, Sequence[str], None] = '2a4a153b31f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))
    op.execute("""
    UPDATE users
    SET nickname = split_part(email, '@', 1)
    WHERE nickname IS NULL
    """)
    op.alter_column(
        "users",
        "nickname",
        nullable=False,
    )
    op.create_unique_constraint(
        "uq_users_nickname",
        "users",
        ["nickname"]
    )
    op.create_index(op.f('ix_users_nickname'), 'users', ['nickname'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_nickname'), table_name='users')
    op.drop_column('users', 'nickname')
    # ### end Alembic commands ###
